package:
  name: nxrefine
  version: "0.1.0"

source:
  git_url: https://github.com/rayosborn/nxrefine.git
  git_tag: v0.1.0

build:
  entry_points:
    - nxsetup=nxrefine.scripts.nxsetup:main
    - nxcopy=nxrefine.scripts.nxcopy:main
    - nxlink=nxrefine.scripts.nxlink:main
    - nxfind=nxrefine.scripts.nxfind:main
    - nxmake=nxrefine.scripts.nxmake:main
    - nxmask=nxrefine.scripts.nxmask:main
    - nxmax=nxrefine.scripts.nxmax:main
    - nxorient=nxrefine.scripts.nxorient:main
    - nxwork=nxrefine.scripts.nxwork:main
    - nxrun=nxrefine.scripts.nxrun:main
    - nxscan=nxrefine.scripts.nxscan:main
    - nxcombine=nxrefine.scripts.nxcombine:main
    - nxtransform=nxrefine.scripts.nxtransform:main
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.6.0

  run:
    - python
    - numpy >=1.6.0
    - sqlalchemy
    - psutil
    - pyfai

test:
  imports:
    - nexusformat
    - nexusformat.nexus

about:
  home: http://nexpy.github.io/nexpy/
  license: BSD License
  summary: 'NXrefine: Python API to refine single crystal x-ray scattering'
